- name: gather ec2 facts
  action: ec2_metadata_facts

- name: reboot the server
  become: true
  command: /sbin/shutdown -r now

- name: wait for host to restart
  local_action:
    module: wait_for
    ost: "{{ ansible_ec2_local_ipv4 }}"
    port: 22
    delay: 1
    timeout: 300