- name: gather ec2 facts
  action: ec2_metadata_facts

- name: Stop AEM service
  shell:
   "sudo /etc/init.d/{{ aem_service_name }} stop"
  register: cmdline
  become: true


- name: Check process
  shell:
   ps -elf | grep java | grep 'adobe*'
  register: cmdline
  failed_when: "cmdline.rc > 1"
  until: cmdline.rc == 1
  retries: 12
  delay: 10