---

- name: " Patching on AEM servers "
  hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}Dispatcher:&tag_AEMInstance_NO:&tag_Name_{{Disp_Name}}"
  user: ubuntu
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:
    
      - name: gather ec2 facts
        action: ec2_metadata_facts

      - include_tasks: ../tasks/aem_apply_patches_server.yml

      - include_tasks: ../tasks/aem_reboot_server.yml

