---

- hosts: "localhost"
  user: ubuntu
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:

      - name: gather ec2 facts
        action: ec2_metadata_facts

      - include_tasks: ../tasks/kube_get_list_pods_label.yml
