- import_playbook: plays/aem_install_packages.yaml
  vars:
    Environment: "{{ Environment }}"
    Usage: "{{ Usage }}"
    Role: "{{ Role }}"
    deploy_type: "task_deploy"

- import_playbook: s3_delete_bucket_aem_files.yaml
  vars:
    Environment: "{{ Environment }}"
    Usage: "{{ Usage }}"
    Role: "{{ Role }}"
    deploy_type: "task_deploy"