---
- hosts:
  user: "{{ user }}"
  serial: 1
  become: true
  tasks:

  - name: Create partition sdc1
  	parted:
    	device: /dev/sdc
    	number: 1
    	flags: [ lvm ]
    	state: present
    	part_start: 2048
    	part_end: 75497471
  
  - name: Create partition sdc2
    parted:
    	device: /dev/sdc
    	number: 2
    	flags: [ lvm ]
    	state: present
    	part_start: 75497472
    	part_end: 251658239
